FROM ubuntu:xenial

RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install -y autoconf automake bison build-essential clang debhelper devscripts doxygen fakeroot flex g++ git graphviz libncurses5-dev libsqlite3-dev libtool make mcpp pkg-config python sqlite zlib1g-dev
