FROM oraclelinux:7.3

RUN yum install -y \
        autoconf \
        automake \
        bison \
        clang \
        doxygen \
        flex \
        gcc-c++ \
        git \
        kernel-devel \
        ncurses-devel \
        sqlite-devel \
        libtool \
        make \
        mcpp \
        pkg-config \
        python \
        sqlite \
        zlib-devel

RUN yum install -y http://dl.fedoraproject.org/pub/fedora/linux/releases/27/Everything/x86_64/os/Packages/l/libmcpp-2.7.2-19.fc27.x86_64.rpm
RUN yum install -y http://dl.fedoraproject.org/pub/fedora/linux/releases/27/Everything/x86_64/os/Packages/m/mcpp-2.7.2-19.fc27.x86_64.rpm

ARG SOUFFLE_GITHUB_USER
ARG SOUFFLE_GIT_BRANCH
ARG SOUFFLE_GIT_REVISION
ARG SOUFFLE_OPTIONS

COPY docker/run.sh run.sh
RUN chmod +x run.sh
RUN SOUFFLE_GITHUB_USER="${SOUFFLE_GITHUB_USER}" SOUFFLE_GIT_BRANCH="${SOUFFLE_GIT_BRANCH}" SOUFFLE_GIT_REVISION="${SOUFFLE_GIT_REVISION}" SOUFFLE_OPTIONS="${SOUFFLE_OPTIONS}" ./run.sh
