FROM oraclelinux:7.3

yum install -y \
    autoconf \
    automake \
    bison \
    clang \
    doxygen \
    flex \
    gcc-c++ \
    git \
    kernel-devel \
    ncurses-devel \
    sqlite-devel \
    libtool \
    make \
    mcpp \
    pkg-config \
    python \
    sqlite \
    zlib-devel

yum install -y http://dl.fedoraproject.org/pub/fedora/linux/releases/27/Everything/x86_64/os/Packages/l/libmcpp-2.7.2-19.fc27.x86_64.rpm
yum install -y http://dl.fedoraproject.org/pub/fedora/linux/releases/27/Everything/x86_64/os/Packages/m/mcpp-2.7.2-19.fc27.x86_64.rpm

ARG GIT_USER
ARG GIT_BRANCH
ARG GIT_REVISION
ARG SOUFFLE_OPTIONS

WORKDIR /souffle
RUN git clone https://github.com/${GIT_USER}/souffle /souffle
RUN git checkout ${GIT_BRANCH} ${GIT_REVISION}
RUN ./bootstrap
RUN ./configure ${SOUFFLE_OPTIONS}
RUN make
RUN /souffle/src/souffle
RUN make install
RUN souffle
